baseurl = "/"
languageCode = "en-us"
title = "Camunda Team Blog"
theme = "blogcamundaorg"
preservetaxonomynames = true
# uglyurls = true
pygmentsStyle  = "github"


# [taxonomies]
#   tag = "tags"
#   category = "categories"
#   author = "authors"

# pagination setup
# https://gohugo.io/templates/pagination/
Paginate = 5


[params]
  repo = "camunda/blog.camunda.org"
  gaCode = "UA-39060941-1"
  disqusShortname = "camundablog"
  gSearchApiKey= "AIzaSyBr7ZsDDbUbl_pExzErrTlSWXSZP0vpzyM"
  gSearchCtx= "007121298374582869478:-vzd0u36nki"
